In [1]:
import numpy as np




In [2]:
np.set_printoptions(precision=3, suppress=True)


In [3]:
X = np.array([[0, 1], [1, 0]])
print(X)

[[0 1]
 [1 0]]


In [4]:
IX = np.kron(np.eye(2), X)                             
print(IX)


[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


In [5]:
XI = np.kron(X, np.eye(2))
print(XI)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [6]:
P = - (IX + XI)
print(P)

[[-0. -1. -1. -0.]
 [-1. -0. -0. -1.]
 [-1. -0. -0. -1.]
 [-0. -1. -1. -0.]]


In [7]:
λ, v = np.linalg.eigh(P)
print("Eigenvalues:", λ)
print("Eigenstate for lowest eigenvalue", v[:, 0])

Eigenvalues: [-2. -0.  0.  2.]
Eigenstate for lowest eigenvalue [-0.5 -0.5 -0.5 -0.5]


DWAVE Annealers

In [12]:
import dimod


In [13]:
linear={('x'):3, ('y'):2, ('z'):-5}
print(linear)


{'x': 3, 'y': 2, 'z': -5}


In [14]:
quadratic={('x','y'):1, ('x','z'):-3.5, ('y','z'):4}
print(quadratic)

{('x', 'y'): 1, ('x', 'z'): -3.5, ('y', 'z'): 4}


In [15]:
vartype = dimod.BINARY
bqm = dimod.BinaryQuadraticModel(linear, quadratic,vartype)

In [16]:
sampler = dimod.ExactSolver()
response = sampler.sample(bqm)
print(response)

   x  y  z energy num_oc.
6  1  0  1   -5.5       1
7  0  0  1   -5.0       1
0  0  0  0    0.0       1
4  0  1  1    1.0       1
5  1  1  1    1.5       1
3  0  1  0    2.0       1
1  1  0  0    3.0       1
2  1  1  0    6.0       1
['BINARY', 8 rows, 8 samples, 3 variables]
